# This runs jobs which pyiron modules should run on release
# This job runs on pull requests and does not actually publish anything to pypi
# It is useful for debugging new build recipes
# To actually release, change the `on` and `publish-to-pypi` fields
name: Preview Release

on:
  release:
    types: [ published ]

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/pyproject-release.yml@actions-4.0.2
    secrets: inherit
    with:
      runner: 'ubuntu-22.04' # with ubuntu > 22.04, pip is broken
      semantic-upper-bound: 'minor'
      lower-bound-yaml: '.ci_support/lower_bound.yml'
      publish-to-pypi: true
